openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /healthcheck:
    get:
      operationId: getHealthcheck
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: boolean
  /user/reviews/{userId}:
    get:
      operationId: getUserReviewsUserid
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /user/bookings/{userId}:
    get:
      operationId: getUserBookingsUserid
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    Booking:
      required:
      - bookingDate
      - bookingId
      - bookingStatus
      - checkInDate
      - checkOutDate
      - confirmationNumber
      - hotelId
      - numberOfGuests
      - pricing
      - primaryGuest
      - rooms
      - specialRequests
      - userId
      type: object
      properties:
        bookingId:
          type: string
        hotelId:
          type: string
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/RoomConfiguration'
        userId:
          type: string
        checkInDate:
          type: string
        checkOutDate:
          type: string
        numberOfGuests:
          type: integer
          format: int64
        primaryGuest:
          $ref: '#/components/schemas/GuestDetails'
        pricing:
          type: array
          items:
            $ref: '#/components/schemas/BookingPricing'
        bookingStatus:
          type: string
        bookingDate:
          type: string
        confirmationNumber:
          type: string
        specialRequests:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/SpecialRequests'
      additionalProperties: false
    BookingPricing:
      required:
      - currency
      - numberOfNights
      - roomRate
      - serviceFees
      - subtotal
      - taxes
      - totalAmount
      type: object
      properties:
        roomRate:
          type: number
          format: double
        numberOfNights:
          type: integer
          format: int64
        subtotal:
          type: number
          format: double
        taxes:
          type: number
          format: double
        serviceFees:
          type: number
          format: double
        totalAmount:
          type: number
          format: double
        currency:
          type: string
      additionalProperties: false
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
    GuestDetails:
      required:
      - email
      - firstName
      - lastName
      - nationality
      - phoneNumber
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        nationality:
          type: string
          nullable: true
      additionalProperties: false
    Review:
      required:
      - categories
      - comment
      - hotelId
      - isVerifiedStay
      - rating
      - reviewDate
      - reviewId
      - title
      - userId
      - userName
      type: object
      properties:
        reviewId:
          type: string
        hotelId:
          type: string
        userId:
          type: string
        userName:
          type: string
        rating:
          type: number
          format: double
        title:
          type: string
        comment:
          type: string
        reviewDate:
          type: string
        categories:
          $ref: '#/components/schemas/ReviewCategories'
        isVerifiedStay:
          type: boolean
      additionalProperties: false
    ReviewCategories:
      required:
      - cleanliness
      - comfort
      - location
      - service
      - valueForMoney
      type: object
      properties:
        cleanliness:
          type: number
          format: double
        comfort:
          type: number
          format: double
        location:
          type: number
          format: double
        service:
          type: number
          format: double
        valueForMoney:
          type: number
          format: double
      additionalProperties: false
    RoomConfiguration:
      required:
      - numberOfRooms
      - roomId
      type: object
      properties:
        roomId:
          type: string
        numberOfRooms:
          type: integer
          format: int64
      additionalProperties: false
    SpecialRequests:
      required:
      - accessibilityNeeds
      - bedPreference
      - dietaryRequirements
      type: object
      properties:
        dietaryRequirements:
          type: string
          nullable: true
        accessibilityNeeds:
          type: string
          nullable: true
        bedPreference:
          type: string
          nullable: true
        petFriendly:
          type: boolean
        otherRequests:
          type: string
      additionalProperties: false
